version: '3.8'

services:
  db:
    image: 'postgres:16'
    container_name: article-kraft
    environment:
      - POSTGRES_DB=$POSTGRESQL_DATABASE
      - POSTGRES_PASSWORD=$POSTGRESQL_PASSWORD
      - POSTGRES_USER=$POSTGRESQL_USER
    env_file:
      - './.env'
    ports:
      - '5432:5432'
    restart: always
