# Profile
ACTIVE_PROFILE: dev

# Database
POSTGRESQL_USERNAME: brandon
POSTGRESQL_PASSWORD: password
POSTGRESQL_HOST: 127.0.0.1
POSTGRESQL_PORT: 5432
POSTGRESQL_DATABASE: article_kraft

# Server
CONTAINER_PORT: 9090

# openai
OPENAI_API_KEY: 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
